services:
  flask-app-1:
    image: umer4444/my-app:${APP1_IMAGE_TAG}
    ports:
      - "8001:8000"
    restart: always

  flask-app-2:
    image: umer4444/my-app:${APP2_IMAGE_TAG}
    ports:
      - "8002:8000"
    restart: always